version: '3.8'

services:
  mongo:
    image: mongo:5
    container_name: JSF-600-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: JSF-600-back
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatDB

  front:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: JSF-600-front
    ports:
      - "3000:3000"
    depends_on:
      - back

volumes:
  mongo_data:
